---
- name: Include normalize_datasets
  ansible.builtin.include_tasks: normalize_datasets.yml
  when: sanoid_datasets | type_debug == "dict"

- name: Include normalize_templates
  ansible.builtin.include_tasks: normalize_templates.yml
  when: sanoid_templates | type_debug == "dict"

- name: Install Sanoid package
  ansible.builtin.package:
    name: "{{ sanoid_package }}"
    state: present

- name: Create Sanoid configuration directory
  ansible.builtin.file:
    name: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Copy Sanoid template
  ansible.builtin.template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - "/etc/sanoid/sanoid.conf"

- name: Retrieve Sanoid binary path
  command: which sanoid
  register: sanoid_cmd_path

- name: Add Sanoid service
  ansible.builtin.template:
    src: sanoid.service.j2
    dest: "/etc/systemd/system/sanoid.service"
    mode: u=rw
    owner: root
    group: wheel

- name: Add Sanoid timer
  ansible.builtin.copy:
  src: sanoid.timer
  dest: "etc/systemd/system/sanoid.timer"
  mode: u=rw
  owner: root
  group: wheel
